In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
def cost (iniclus, clus, X):
  m, n= X.shape
  j=0
  for i in range (m):
    dist=np.sum((X[i]-iniclus[int(clus[i])])**2)
    j=j+dist
  return j/m

In [ ]:
def scaling(X):
  m, n=X.shape
  for j in range(n):
    X[:,j]=(X[:,j]-np.mean(X[:,j]))/np.std(X[:,j])
  return X

In [ ]:


def Kmeans(X, k, ittr):
    m, n = X.shape
    np.random.seed(42)
    centroids = X[np.random.choice(m, k, replace=False)]
    clusters = np.zeros(m)

    for i in range(ittr):

        for j in range(m):
            distances = np.sum((X[j] - centroids) ** 2, axis=1)
            clusters[j] = np.argmin(distances)


        new_centroids = np.array([X[clusters == t].mean(axis=0) if len(X[clusters == t]) > 0 else centroids[t] for t in range(k)])

        if np.allclose(centroids, new_centroids, atol=1e-4):
            print(f"Convergence reached at iteration {i}")
            break

        centroids = new_centroids


        if i % 10 == 0:
            cost = np.mean([np.sum((X[clusters == t] - centroids[t]) ** 2) for t in range(k)])
            print(f"Cost after {i} iterations: {cost}")

    print(f"Final centroids:\n{centroids}")
    print(f"Cluster assignments:\n{clusters + 1}")


In [ ]:
'''X=np.array([[1, 2, 3], [4, 5, 6], [7 , 8,9], [10, 11, 12]])
print(Kmeans (X, 2, 10))'''

'X=np.array([[1, 2, 3], [4, 5, 6], [7 , 8,9], [10, 11, 12]])\nprint(Kmeans (X, 2, 10))'

In [ ]:
data=np.array(pd.read_csv("unsupervised_data.csv"))
a, b=np.shape(data)


In [ ]:
X=np.zeros([a,b-1])


for i in range (a):
  X[i]=data[i, 1:b]


In [ ]:
print(X)

[[-21.90459052 -22.65909077  12.80599532 -46.63193454 -34.34708058
  -21.98973763]
 [-28.6623852   68.7570811   31.76182149   3.98225896 -62.87686557
  -61.83856263]
 [-62.55120406  60.90923463   8.11291761  24.1100498  -64.37233589
   70.68194042]
 ...
 [-10.5193655   51.35470206 -45.12963703   1.94184293  13.16236957
  -77.77000929]
 [ 47.12231456 -47.27290614 -47.18462792 -52.90839123 -29.80429118
    2.04282004]
 [-12.18331877  52.25702955 -42.01543172  14.20654525   0.70609201
  -77.29727207]]


In [ ]:
X=scaling(X)
print(X)

[[-0.35139799 -0.37542604  0.54841073 -1.14716136 -0.24047117 -0.3996431 ]
 [-0.54362329  1.35051141  1.01882703  0.07881007 -0.84592181 -1.23656397]
 [-1.5075899   1.20234405  0.43194521  0.56634321 -0.87765824  1.54668434]
 ...
 [-0.02754555  1.02195447 -0.88934594  0.02938734  0.76776029 -1.57116255]
 [ 1.61207061 -0.84013491 -0.94034352 -1.299189   -0.14406544  0.10509823]
 [-0.07487666  1.03899041 -0.81206242  0.32646161  0.50341686 -1.56123394]]


In [ ]:
Kmeans(X, 10, 100)

Cost after 0 iterations: 2775.171507213574
Cost after 10 iterations: 595.9587090265013
Cost after 20 iterations: 595.658526627734
Convergence reached at iteration 28
Final centroids:
[[-1.5042706   1.11924844  0.62301111  0.75432022 -1.07425164  1.57869635]
 [ 1.88567746 -0.78296488 -0.99051721 -1.18530071 -0.15015331  0.14007246]
 [-0.27692132  1.36288055  1.11651109  0.35123203 -0.63511334 -1.05267776]
 [ 0.07916374  0.88244909 -0.91566407  0.03125732  0.78937109 -1.40254636]
 [-1.81952201  1.1158565   0.61452537  0.76273566 -1.07824661  1.58286284]
 [ 1.56754729 -0.78060839 -0.98003856 -1.21530575 -0.1486838   0.14004613]
 [-0.4261687  -1.11346628  0.92996938 -0.2259948  -0.74785305  0.04860984]
 [-0.74141851 -1.11813207  0.93865075 -0.25356057 -0.75148831  0.05230724]
 [-0.02341114 -0.55636445  0.65967335 -1.36000115 -0.18900128 -0.37172409]
 [ 0.74299158 -0.90934863 -1.42864777  1.65898792  2.01039933  1.05553676]]
Cluster assignments:
[9. 3. 1. ... 4. 6. 4.]
